In [3]:
import numpy as np

### Multiply the following vectors and matrices:

In [16]:
matrix_a = np.array([[2, 1],
                 [1, 2]])
matrix_b = np.array([[1],
                 [1]])

result = np.dot(matrix_a, matrix_b)
result

array([[3],
       [3]])

In [15]:
matrix_a = np.array([[2, 1],
                 [1, 2]])
matrix_b = np.array([[1],
                 [-1]])

result1 = np.dot(matrix_a, matrix_b)
result1

array([[ 1],
       [-1]])

In [17]:
matrix_a = np.array([[1, 2],
                 [3, 4]])
matrix_b = np.array([[5, 6],
                 [7, 8]])
result2 = np.dot(matrix_a, matrix_b)
result2

array([[19, 22],
       [43, 50]])

In [ ]:
matrix_a = np.array([[1, 2],
                 [3, 4]])
matrix_b = np.array([[5, 6],
                 [7, 8]])
result2 = np.dot(matrix_a, matrix_b)
result2

In [19]:
matrix_a = np.array([[1, -1],
                 [1, 1]])
matrix_b = np.array([[1, 1],
                 [-1, 1]])
result3 = np.dot(matrix_a, matrix_b)
result3

array([[2, 0],
       [0, 2]])

In [20]:
matrix_a = np.array([[-1, 0, 0],
                 [0, 0, -1],
                    [0, 1, 0]])
matrix_b = np.array([[-1, 0, 0],
                 [0, 0, 1],
                    [0, -1, 0]])
result4 = np.dot(matrix_a, matrix_b)
result4

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])